package dasturlash.warehouse_zero

enum class Status {
    ACTIVE, INACTIVE
}

enum class Role {
    ROLE_EMPLOYEE, ROLE_ADMIN
}

enum class ErrorCode(val code: Int, val message: String) {
    //1
    WAREHOUSE_ALREADY_EXISTS(100, "WAREHOUSE_ALREADY_EXISTS"),
    WAREHOUSE_NOT_FOUND(101, "WAREHOUSE_NOT_FOUND"),
    //2
    EMPLOYEE_NOT_FOUND(200, "EMPLOYEE_NOT_FOUND"),
    //3
    INVALID_PASSWORD(300, "INVALID_PASSWORD"),
    //4
    CATEGORY_ALREADY_EXISTS(400, "CATEGORY_ALREADY_EXISTS"),
    CATEGORY_NOT_FOUND(401, "CATEGORY_NOT_FOUND"),
    //5
    PRODUCT_NOT_FOUND(500, "PRODUCT_NOT_FOUND"),
    //6
    MEASUREMENT_NOT_FOUND(600, "MEASUREMENT_NOT_FOUND"),
    MEASUREMENT_ALREADY_EXISTS(601, "MEASUREMENT_ALREADY_EXISTS"),
}