package dasturlash.warehouse_zero

enum class Status {
    ACTIVE, INACTIVE
}

enum class StockInOutProcessingStatus{
    DRAFT, COMPLETED
}

enum class Role {
    ROLE_EMPLOYEE, ROLE_ADMIN
}

enum class ErrorCode(val code: Int, val message: String) {
    //1
    WAREHOUSE_ALREADY_EXISTS(100, "WAREHOUSE_ALREADY_EXISTS"),
    WAREHOUSE_NOT_FOUND(101, "WAREHOUSE_NOT_FOUND"),
    //2
    EMPLOYEE_NOT_FOUND(200, "EMPLOYEE_NOT_FOUND"),
    EMPLOYEE_ALREADY_EXISTS(201, "EMPLOYEE_ALREADY_EXISTS"),
    EMPLOYEE_NOT_AUTHENTICATED(202, "EMPLOYEE_NOT_AUTHENTICATED"),
    //3
    INVALID_PASSWORD(300, "INVALID_PASSWORD"),
    //4
    CATEGORY_ALREADY_EXISTS(400, "CATEGORY_ALREADY_EXISTS"),
    CATEGORY_NOT_FOUND(401, "CATEGORY_NOT_FOUND"),
    //5
    PRODUCT_NOT_FOUND(500, "PRODUCT_NOT_FOUND"),
    PRODUCT_ALREADY_EXISTS(501, "PRODUCT_ALREADY_EXISTS"),
    //6
    MEASUREMENT_NOT_FOUND(600, "MEASUREMENT_NOT_FOUND"),
    MEASUREMENT_ALREADY_EXISTS(601, "MEASUREMENT_ALREADY_EXISTS"),
    //7
    PRODUCT_NOT_IN_STOCK(700, "PRODUCT_NOT_IN_STOCK"),
    //8
    ATTACH_NOT_FOUND(800, "ATTACH_NOT_FOUND"),
    //9
    PHONE_NUMBER_NOT_FOUND(900, "PHONE_NUMBER_NOT_FOUND"),
    SUPPLIER_NOT_FOUND(901, "SUPPLIER_NOT_FOUND"),
    //10
    CURRENCY_NOT_FOUND(1000, "CURRENCY_NOT_FOUND"),
    CURRENCY_ALREADY_EXISTS(1001, "CURRENCY_ALREADY_EXISTS"),

}